# Generated by Django 3.2.6 on 2021-08-05 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0002_auto_20210804_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='games', to=settings.AUTH_USER_MODEL),
        ),
    ]
