# Generated by Django 3.2.6 on 2021-08-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20210805_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='comentario',
            field=models.TextField(default=''),
        ),
    ]
