# Generated by Django 3.2.6 on 2021-08-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_game_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='comentario',
            field=models.TextField(default='', null=True),
        ),
    ]
