# Generated by Django 3.2.6 on 2021-08-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_game_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='dataLancamento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='dataUltimoJogo',
            field=models.DateField(null=True),
        ),
    ]
