# Generated by Django 3.2.6 on 2021-08-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_auto_20210810_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='comentario',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
